[package]
name = "zcapjson"
version = "0.1.0"
authors = ["Amanjeev Sethi <aj@amanjeev.com>"]
edition = "2018"

[dependencies]
serde = "1.0.125"
serde_json = "1.0.64"
simd-json-derive = "0.2.2"
simd-json = { version = "0.4", features = ["known-key", "serde_impl"] }
simd-json-derive-int = "0.2.0"
